// Generated by https://quicktype.io

export interface Favorite {
    status_code:    number;
    status_message: string;
}

export interface Watchlist {
    status_code:    number;
    status_message: string;
}
