// Generated by https://quicktype.io

import { Movie } from "./movie-list.module";

export interface FavoritesMoviesResponse {
  page:          number;
  results:       Movie[];
  total_pages:   number;
  total_results: number;
}


