// Generated by https://quicktype.io

import { Serie } from "./serie-list.module";

export interface FavoriteSeriesResponse {
  page:          number;
  results:       Serie[];
  total_pages:   number;
  total_results: number;
}


