// Generated by https://quicktype.io

import { Movie } from "./movie-list.module";

export interface NowPlaying {
    dates:         Dates;
    page:          number;
    results:       Movie[];
    total_pages:   number;
    total_results: number;
}

export interface Dates {
    maximum: string;
    minimum: string;
}



export enum OriginalLanguage {
    En = "en",
    Es = "es",
    Uk = "uk",
}
